### ISSUE TITLE
DataType "Move" event doesn't trigger artifact update

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Deploy.Issues#10]
On a Cloud project, regardless of environment, if you **Move** a DataType (to a folder), the `*.uda` artifact isn't updated.

For my scenario, on my local environment, I moved a custom DataType entity to a sub folder (for organisation). There were no local changes in my Git repository.  This meant that I could no longer deploy or restore content (that used that DataType), as there was a schema type mismatch between my local and the Development environments.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I suspect that Umbraco Deploy isn't hooked up to the DataType.Move event.
If I re-save the DataType, the `*.uda` artifact file is updated as expected.

### Specifics

* Umbraco CMS v7.11.2
* Umbraco Deploy v2.0.14
* Win10/Chrome _(TBH, I don't think the browser is relevant in this case)_

### Steps to reproduce

* On a local environment, in the CMS back-office, go to the "Developer" section
* In the "Data Types" tree, select any DataType, select "Move" (from either the "Action" menu or right-click context menu).
* Move the DataType to another folder. **(If you don't have another folder, please create one)**
* Check your local Git repository for any `*.uda` artifact changes.

### Expected result

I expected the `*.uda` artifact file to be updated when I moved the DataType to another folder.

### Actual result

The actual result was that the `*.uda` artifact file wasn't updated on my local file system.

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Umbraco-Deploy/pull/481
Due for 4.1.1 release
