### ISSUE TITLE
Forms - Partial restore selects from content tree rather than forms

### ISSUE THREAD

**Issue by md-hc** [umbraco/Umbraco.Deploy.Issues#100]
When using "Partial restore" it is not possible to select a form, as "select content to restore" opens the content tree rather than forms

![Capture](https://user-images.githubusercontent.com/89011740/152541730-c9c384f4-7197-446b-bc20-9cdbbb040ae3.PNG)

**Comment by AndyButland** [comment]
I think you'll find on a more recent version that what I assume you are running, this button is hidden for forms.  Would like to have a look in an upcoming sprint to see if we can support this, as it would be useful, but it's a little tricky given CMS, Forms and Deploy are all separate products that might be running in different combinations of versions.  It's on the list though to at least investigate.
