### ISSUE TITLE
9.3RC - Feedback on Deploy "Compare" dialog

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#101]
The new "Compare" dialog works well, and it's great to see exactly what has changed, per property. A few things which would be nice additions, if possible:

1. Include the **User** who last edited the local/remote versions. This would help developers avoid overwriting Content Editor's work on other environments. 
2. Consider putting the User/Date info into a tabular format to make it easier to visually scan/compare.
3. If possible, include other contextual information, like number of descendant nodes, parent node name (to indicate moved nodes), etc...
4. It would also be helpful to include at the bottom of the dialog some additional buttons: "Transfer Now", "Queue for Transfer", and "Restore".

![image](https://user-images.githubusercontent.com/1252593/155808509-59c6e7f8-da5b-4ac5-aaf8-f226778001cc.png)

**Comment by AndyButland** [comment]
Thanks again for the suggestions @hfloyd.  These additional details and action buttons have been added to the dialog for the next release.
