### ISSUE TITLE
Content culture/language not restoring

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco.Deploy.Issues#107]
After locally restoring a website, the content culture/language isn't restored.

Reproduction
------------
### Bug summary
If a content node has a culture/language set (from the dropdown in the 'Culture and Hostnames' action), this isn't restored or published.

Just to be clear: this is not on the domain, but the actual node itself.

### Specifics
Tested with Umbraco 7.12+ and Umbraco Deploy 2.0.14.

### Steps to reproduce
* Set a culture/language on a content node
* Locally restore the whole website

### Expected result
I would expect the culture/language to also be synced.

### Actual result
It's restored with the default 'Inherit' value.

**Comment by AndyButland** [comment]
Due in 4.6.0/9.4.0.
