### ISSUE TITLE
Umbraco 9 - "The service is unavailable." after deploying changes including .uda files

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#109]
### Issue description

I am working on a site which hasn't launched yet. Primarily I work on local, and we have 1 Cloud environment setup (live), which gets deployed-to when I GIT push from local. 

Something I have noticed on a regular basis (haven't tested if this is 100% of the time, but frequently enough to be problematic) is that if I push up some .uda files, then visit the live cloud site, I see the message "The service is unavailable.":
![image](https://user-images.githubusercontent.com/1252593/164533058-8b9358ce-3519-4627-b0d1-6e2ab3135d84.png)

This remain the case 15+minutes after the deployment, so it's not a quick automatic site restart sort of thing.

I have to go into the Cloud Portal and trigger a restart:
![image](https://user-images.githubusercontent.com/1252593/164533447-41af829c-9cbc-406c-8562-c5c820e8a322.png)

Incidentally, if I then immediately look at the site I see this DIFFERENT "Unavailable" message:
![image](https://user-images.githubusercontent.com/1252593/164533658-11bfac9f-4dc3-4e06-80e0-f53979e0fe68.png)

After the expected minute or so, I can refresh and the site loads fine. It's just annoying that I have to always restart the site manually after a GIT push.

It seems that if the deployment doesn't include UDA files (just CSS or View file updates, for instance) the "unavailable" issue doesn't occur.

**Comment by hfloyd** [comment]
Ok, the next time I do a push which results in these issues, I will reach out to support. This specific project is scheduled to go live early next week, and I might not have any more UDA changes to push for a bit.

**Comment by ronaldbarendse** [comment]
Hi Heather! This seems like the same issue as reported in https://github.com/umbraco/Umbraco.Deploy.Issues/issues/108 and should be solved with the same fix in the CMS... I'll also close this one, but as usual, please let us know if you notice similar issues in the latest versions 😄
