### ISSUE TITLE
Empty MultiUrlPicker property gets added to the database

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Deploy.Issues#112]
Seems like an old ghost 👻 is haunting us again:
The ghost in question is this one:
https://github.com/umbraco/Umbraco.Deploy.Issues/issues/104

When trying to transfer a MultiUrlPicker from for example local to Cloud, Deploy is creating an empty row in the database.
Unless you check for this empty value in code, the site/code will break, as it expects a string or null value.

Reproduction
------------
I create an empty content node, which has a MultiUrlPicker property.
I save and publish the content node with no values added to the MultiUrlPicker
If I now connect to the database and run this query it will reveal what property values there are for the published version of the content node
```
SELECT TOP (1000) [umbracoPropertyData].[id]
      ,[versionId]
      ,[propertyTypeId]
      ,[languageId]
      ,[segment]
      ,[intValue]
      ,[decimalValue]
      ,[dateValue]
      ,[varcharValue]
      ,[textValue]
      ,[propertyEditorAlias]
      ,[cmsPropertyType].Alias
  FROM [clientiV9].[dbo].[umbracoPropertyData]
      INNER JOIN umbracoContentVersion on umbracoContentVersion.id = umbracoPropertyData.versionId
      INNER JOIN [cmsPropertyType] on [cmsPropertyType].id = umbracoPropertyData.propertyTypeId
      INNER JOIN [umbracoDataType] on [umbracoDataType].nodeId = cmsPropertyType.dataTypeId
  WHERE umbracoContentVersion.nodeId = 1250 and [current] = 1 
```

**LOCAL** 
![local](https://user-images.githubusercontent.com/2794633/165698337-6cf1277d-54e0-4679-b6d0-96e6ca4c0ce1.png)

From having run the query above locally, notice that there is no row with the MulitUrlPicker. 
When you transfer this node to the next environment (Live in this case) and run the query against that database the values will look like this:

**LIVE**
![live](https://user-images.githubusercontent.com/2794633/165698394-a70dbf59-819a-4f63-8d83-83d84e13de41.png)

There are more rows for that node and the new rows have empty values. 

Kudos to Halldór for helping me discovering this 🤟

### Bug summary
Deploy should not create the empty rows in the db.
 

### Specifics
Tested on:
- Umbraco 9.4.3
- Deploy 9.3.1

### Expected result
Deploying this should ... work? 😅

### Actual result
The site will break and return a HTTP 500 error

**Comment by AndyButland** [comment]
Hi - just trying to replicate this with the latest code, but I'm not seeing it.  I get the record removed in the upstream environment as you'd expect.  Would you mind re-testing with Deploy 9.4 and let me know if you still have the issue please?  Thanks.

If so, can you share the project exhibiting the issue so I can have a closer look please?  Thanks.

**Comment by HamDerAndrew** [comment]
Upgrading to 9.4 fixed the issue 👍
