### ISSUE TITLE
Make deploy operations self explanatory

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Deploy.Issues#118]
I would like to see separate buttons with an explanation for the deploy operations on the deploy dashboard.
It is not clear for new users when to use what and especially since it's hidden in a dropdown.

Maybe we could make it like the published status actions?

So go from this:
![image](https://user-images.githubusercontent.com/29602162/170032709-63052269-7f48-4628-8f94-93e2c914daa7.png)

To something like this?:
![image](https://user-images.githubusercontent.com/29602162/170032795-d412f1ef-2f2f-486c-a0db-d0dc20a771e9.png)

**Comment by AndyButland** [comment]
Sounds a good idea to me.  Here's what we'll have with the next update:

![image](https://user-images.githubusercontent.com/1993459/178990746-a607ab37-7eb7-434c-8762-ee2126356fa4.png)

**Comment by AndyButland** [comment]
Good point.  How about?

_Clear the cached artifact signatures from the Umbraco environment.
This should not be necessary in normal use but if editors are getting reports of schema mismatches when environments have been aligned, clearing this cached data may resolve the situation._

**Comment by FransdeJong** [comment]
So that is the button I need to press when I get random mismatches on a new environment? 🤣

Maybe it could be finetuned to:
_This should not be necessary in normal use.  This may solve reports of schema mismatches when transferring content between environments that have been aligned._

It doesn't really matter who runs into these issues.

**Comment by AndyButland** [comment]
That's the one :-)

Sounds good, we'll go with that.  Thanks for your input!
