### ISSUE TITLE
Add deploy error log to the deploy dashboard

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Deploy.Issues#120]
Can we add the deploy error file to the deploy dashboard?
If I trigger a deploy from the dashboard and get an error then I need to go to Kudu and login to see the log.
It seems like a small addition to add the logfile to the dashboard and refresh after every deploy?

Especially if it can be in a separate tab on a deploy section like described [here](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/119)?

**Comment by AndyButland** [comment]
Thanks for the suggestion Frans - we've added this now to the dashboard so it'll be available in the next release.

![image](https://user-images.githubusercontent.com/1993459/170691432-f9432f04-0f5d-4167-825a-dd1fb4d94273.png)

![image](https://user-images.githubusercontent.com/1993459/170691451-2470abbe-b4df-47bb-a5cb-1cf881a17d40.png)
