### ISSUE TITLE
Copy Button to the deploy log in Back Office 

### ISSUE THREAD

**Issue by PratheesUmbraco** [umbraco/Umbraco.Deploy.Issues#121]
Its hard to copy the error message in the Back Office when content transferring and it fails. 

Just to make it easier for us to copy the stack trace it would be awesome to have a button that copies the error message

**Comment by AndyButland** [comment]
Good idea.  I've added this now so it'll be available in the next release.

![image](https://user-images.githubusercontent.com/1993459/170671242-b449da59-6a30-44de-b3ad-3192fdf68b66.png)
