### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by beingonlinedave** [umbraco/Umbraco.Deploy.Issues#122]
Thanks for any help anyone can be.

Following the DevOps example here - https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/installing-deploy/CICD-Pipeline/ci-cd-azure-dev-ops - for Umbraco 9 appears to cause some issues.

Reproduction
------------

### Bug summary

Some of the tasks in the example code do not appear to do what you would want them to do.

### Specifics

Here are the tasks that there appear to be issues with:

Task [#3] Build the VS Solution and publish the output to a directory
It is not copying the App_Plugins folders or their contents

Task [#4] Copy the deploy .lic file as they are not part of the csproj/msbuild
This is not necessary as Umbraco 9 does not use the \bin folder from what I understand it just reads the licence from the \umbraco\Licenses folder

#5 Copy the deploy (data) files since they are not part of the csproj/msbuild
Seems to copy the .uda files into the root directory of the app, whereas they seem to come across in the \umbraco\Deploy\Revisions

### Steps to reproduce

You would have to set it up in Azure Pipelines

### Expected result

I expected the pipeline to run without issue and make a copy of my local codebase on the server

### Actual result

Files appear to be copied into the wrong places on the server

**Comment by AndyButland** [comment]
A page has been published now with the Umbraco 9 example for AzureDevOps, so we now have [V9](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/installing-deploy/CICD-Pipeline/ci-cd-azure-dev-ops) and [V8](https://our.umbraco.com/Documentation/Add-ons/Umbraco-Deploy/Installing-Deploy/CICD-Pipeline/ci-cd-azure-dev-ops-v8) versions.
