### ISSUE TITLE
Umbraco Deploy won't pull if local media files are missing

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Deploy.Issues#123]
With Cloud v9.4.0, 

When media **files** are missing locally, but they do exist in the DB, then trying to pull these media files from another environment will fail.

I presume this is because the Deploy logic tries to generate a hash of the local file, to determine if the remote version is different. Because there is no file, hash generation fails and thus the whole sync fails.

The solution would be always sync media files from a remote environment if the media files are missing. It should be possible to delete the whole media folder locally, and restore it from a remote environment. Even if the DB already contains nodes for the media files.

**Comment by AndyButland** [comment]
I'm not able to replicate this following a quick look... would you mind checking over my steps please to see if you can see I'm missing something/doing something different?

- Start with a media file synchronised between local and a cloud site environments.
- Delete the media file and folder from disk in the local site (i.e. from `/wwwroot/media`).
- Note that the media record exists in the tree, but the image is missing.
- Do a "Tree Restore" on the media section
- I find the image is restored (i.e. the record still exists in the tree, and the file is now on disk).

**Comment by LennardF1989** [comment]
Hello @AndyButland - I did a quick checkup, and it appears to be very conditional: it only happens with file extensions .svg, .mp4 and potentially other "weird" ones. Can confirm .png and .jpg work as you describe.

What I did to make this all happen was pull a copy of the production DB to local, then try to download the media. Looks like this somehow breaks these files then.

However, you can "fix" it by:
- making an empty .svg at the location the error mentions
- try to sync
- it will then complain the file is in use (Windows). 
- If you then restart the full app pool, this image is magically fixed. If you now remove the empty .svg (before starting), it will sync properly. Other .svg's that didn't get this treatment are still broken.

The "in-use" appears to be related to Deploy too. If the process fails like this, it somehow locks the file indefinitely. I had to actually remove the file as explained above to not lock anything and make restore work again. Trying to use a real .svg instead of an empty one doesn't seem to shorten the workaround.

Let me see if I can make a screen recording.

**Comment by LennardF1989** [comment]
Here you go!

![Animatie](https://user-images.githubusercontent.com/869973/172424352-bc35650a-702e-411e-b9cc-f64fdc84640e.gif)

**Comment by AndyButland** [comment]
Thanks for the follow-up and illustrations.  I've been able to replicate now and found the reason for the difference between different media items - it's due to a different property editor (and hence value converter for Deploy) being used for these different media types.  Image types use the image cropper property editor and other files use the file upload one.

I can see the behaviour between these two is different with only the latter throwing an exception, which it looks like it doesn't need to do to restore locally as is required.

A PR has been created - assuming it's approved in review we'll make this available in the next patch release.

**Comment by AndyButland** [comment]
Tested and confirm, this will be available in the next patch release.
