### ISSUE TITLE
Not all document properties get transferred, neither from local to Live nor from Live to local

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Deploy.Issues#126]
### Issue description

What I did:

1. Created a new Umbraco 10 [Cloud Starter project](https://www.s1.umbraco.io/project/idseefeld).
2. Added German as default language (LIVE).
3. Created a contact form and some translations as magic strings (LIVE).
4. Cloned project to localhost.
5. In Visual Studio 2022 added sln-file and class library project _UmbracoProject.Core_.
6. Renamed _UmbracoProject_ to _UmbracoProject.Web_ (updated namespaces, .umbraco)
7. Deleted bin and obj folder.
8. Configured ModelsBuilder to generate models in _UmbracoProject.Core_ with mode _SourceCodeManual_ project in appsetting.devlopment.json.
9. Configured ModelsBuilder mode _Nothing_ in appsetting.json.
10. Generated models in back-office settings section.
11. Restarted with compiled models.
12. Created composition doc type SEO with three properties.
13. Created doc type with template _idsStandard_ using sEO composition and grid property.
14. Created doc type with template _Root_ inheriting from _idsStandard_ and textbox for sitename allowed at root.
14.1. all doc types and properties allow vary by culture
15. Created one content node of type _root_ and filled in the properties.
16. Stopped debugging, build and did git push.
17. Started debugging again and queued the one and only node for transfer.
17.1. On Workspaces started _Transfer to Live_ and got schema mismatch error
19. Reordered properties on sEO doc type, generated models and git push.
19.1. Started debugging again and queued the one and only node for transfer.
19.2. On Workspaces started _Transfer to Live_ and received success message
19.3. In Live environment I see the root node with correct name and template assigned, but none of the properties have their values set.
20. Deleted the Live node and tried transfer from local again. No difference.
21. Filled in all properties on the Live node and deleted the local node.
22. Did a restore on local, but same result of created node without property content.
23. Deleted all local files and did a fresh clone of the project.
24. Build and restored from Live: Same result.

If it might help you can use my project [https://www.s1.umbraco.io/project/idseefeld](https://www.s1.umbraco.io/project/idseefeld)
Do I have to add one of you to the project or do you have already admin access?

I will wait for your response. Continuing to work just doesn't make sense anyways.😥

Yours Dirk

**Comment by idseefeld** [comment]
Thank you, 
I intended to post this here. Probably I got the wrong link. I'll check my bookmarks!

**Comment by AndyButland** [comment]
Would be very useful thanks @idseefeld if you could invite me to the project (abl AT umbraco DOT dk) please.  I can then try restoring and replicating what you are finding.

**Comment by idseefeld** [comment]
Hi Andy, 
I have just invited you to the project and hope it is not a big issue.

**Comment by idseefeld** [comment]
I have found another Deploy documentation page and added the following to appsettings.json:
```
"Deploy": {
      "Settings": {
        "AllowDomainsDeploymentOperations": "All"
      }
    }
```
But that did not help. 

Btw. AllowDomainsDeploymentOperations is not defined in appsettings-schema.json

**Comment by idseefeld** [comment]
Hi @AndyButland now you should have received an invitation. I did a typo in your email.

**Comment by AndyButland** [comment]
Got it now, thanks.

**Comment by AndyButland** [comment]
Thanks again @idseefeld for the report and repro steps.  I've found a bug we've inadvertently introduced with the 10.0 release for restoring content with variant properties, so will get this fixed up for a patch release.

**Comment by AndyButland** [comment]
I've taken the liberty of upgrading the project you shared with me to 10.0.1, and that looks to have resolved the issue.  If I do a restore now of the variant content item, I get all the properties as expected.
