### ISSUE TITLE
UmbracoDeploy 4.6 not available via nuget?

### ISSUE THREAD

**Issue by corsini-iodigital** [umbraco/Umbraco.Deploy.Issues#129]
Hi!

Is it possible that UmbracoDeploy 4.6 is not yet available via nuget?

We have a v8 cloud project with a separate self-hosted repo that pushes to Umbraco Cloud via a pipeline. So far we were always able to upgrade the Deploy packages via the UaaS nuget (https://www.myget.org/F/uaas/api/v3/index.json). Currently the Deploy version on cloud has auto-upgraded to 4.6 but in our repo we cannot upgrade to that version.

Support suggested to do a manual upgrade (https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Manual-upgrades/Manual-Deploy-and-Courier-Upgrade) but we would like to avoid that.

Thanks!

**Comment by AndyButland** [comment]
Hi @corsini-iodigital - you'll find the package there now.  Seems something didn't happen as it should with our automated release, but it's been added manually and we'll include a manual check for future releases.

**Comment by corsini-iodigital** [comment]
Hi @AndyButland, thanks a lot! Can see it now.

Cheers!
