### ISSUE TITLE
The content is null(empty)  after unpublished content transfer/restore 

### ISSUE THREAD

**Issue by alina-tincas** [umbraco/Umbraco.Deploy.Issues#131]
**A brief description of the issue goes here.**
When you transfer/restore a content that is unpublished from one environment to the other (where it is published), then the published one becomes publish(pending changes) with empty content on frontend URL.

**Reproduction**
------------

### Specifics
Tested on Umbraco 8.17.0 and Umbraco 10.0.1.1

### Steps to reproduce
Let´s take this scenario:
- on both envs I have 3 languages: en, da, ro
- on both envs all 3 languages are published
- let´s reproduce this issue by following these steps: 
1. On the dev env I unpublish the Romanian language and then I make a small content change to the Danish version. 
2. I queue for transfer the Danish node from dev to live env. Since am targeting the Danish node I do not expect the Romanian node to be unpublished on the live environment. 
3. When the content transfer has been successfully completed on the live env, the Romanian language becomes from published to published(pending changes). When I access the node of the Romanian language node I get an empty response, even though before transferring the content was there. 
4. I need to save and published the content on live env to make sure it works. 

Restoring gives the same result.

You can also see the attached video:
https://user-images.githubusercontent.com/83591955/178474391-bf36ff7c-02de-4673-96fc-9b99036fd3ac.mp4

### Expected result
What is expected is that the content that was restored/transferred is not empty after it was restored/transferred.

**Comment by AndyButland** [comment]
This behaviour will be changed with the next release,

Currently we aren't handling the case where we have one culture published and another one not, so with the update, rather than always doing a full `SaveAndPublish` for a published document, where we have culture variant content, we only publish the content that's published in the source environment, and unpublish what's not.
