### ISSUE TITLE
Workflow "Save as Umbraco content node" field "Save location"(NodeId) is broken after workspace restore

### ISSUE THREAD

**Issue by ygrave** [umbraco/Umbraco.Deploy.Issues#133]
Hi

We are running Umbraco Cloud. On our Development environment we have Umbraco Forms set up. While setting up local project I restored workspace from our Development environment. I have used this documentation https://our.umbraco.com/documentation/umbraco-cloud/Deployment/Restoring-content/.

After restore I have noticed that field "Save location" of workflow "Save as Umbraco content node" of our forms is empty. But on Development environment it is filled in.

When I open workflow "Save as Umbraco content node" I get an error "Request error: The URL returned a 404 (not found): /umbraco/backoffice/umbracoapi/entity/GetById" error When I try to submit form on local environment I get an error "System.ArgumentException: No content with that id. (Parameter 'parentId')" in log.

I found that field "RootNode" in workflow's json has id of content node from Development environment, but the same node on my local environment has different id(but the same Unique ID). After manual fix of id in database issues with "Save location" and form submitting were fixed.

Is it expected behavior of restore? Is it any way to avoid manual database fixes? Is it any way to change broken "Save location" from UI?

Thanks,

Reproduction
------------

Deploy Umbraco Form from Base line to child and the location is empty and cannot be selected

### Bug summary

    * Write a short summary of the bug
    * Try to pinpoint it as much as possible
    * Try to state the _actual problem_, and not just what you _think_ the
      solution might be.
    * When I deploy from the base line to a child, we lose the location of the workflow. See also attachment for the error.

### Specifics

    Where applicable:
    * [Mention the URL where this bug occurs, if applicable](https://kennisplatform-aol-demo.euwest01.umbraco.io/)
    * What version are you using (Umbraco Form 9.4.2. / Umbraco 9.5.2 / Deploy 9.4.1)
    * What browser and version you are using (All)
    * Please mention if you've checked it in other browsers as well Yes
    * Please include *full error messages* and *screenshots* if possible

### Steps to reproduce

    * Clearly mention the steps to reproduce the bug
    * On Base line a create a Form with a workflow. In this workflow I want to save the form data inside a Umbraco node. I select the correct location and it's working.
    * When I deploy from the Base Line to a child, we lose this location and it's impossible to select again the correct location. 

### Expected result

    * What did you _expect_ that would happen on your site? That the save location of the workflow would be present.
    * Describe the intended/desired outcome after you did the steps mentioned.

### Actual result

<img width="677" alt="ErrorUmbracoFromDeploy" src="https://user-images.githubusercontent.com/33352749/179732527-77f293dd-89d5-4abe-9c6a-12b513158e36.png">

If you need more information, please let me know. 
In advance thanks. #https://our.umbraco.com/forum/using-umbraco-and-getting-started/109239-workflow-save-as-umbraco-content-node-field-save-location-nodeid-is-broken-after-workspace-restore

**Comment by AndyButland** [comment]
Thanks for reporting.  It looks like the integer Id stored for this field isn't being converted when transferring the form information between environments.  This is necessary for certain information stored in Umbraco when the integer Id rather than the GUID key that is common between environments is stored.

I've moved the issue over to the Umbraco Deploy tracker as I believe it's in that product the issue needs to be resolved.

**Comment by ygrave** [comment]
Hi Andy,

What is the next step? When this major bug would be solved? It would be nice to receive a little bit more information.
In advance thanks.

**Comment by AndyButland** [comment]
Next step is that when time permits we'll take a look at this and see if we can resolve it via a patch release.  I expect we'll get to include it in the upcoming sprint, starting next week.

**Comment by ygrave** [comment]
Hi Andy, thanks for these information. It would be nice to receive asap a patch release. We want to deploy a base line project to differents child projects but because of this probleem the all project is onhold! In advance thanks for your answer.

**Comment by AndyButland** [comment]
Fix has been tested and reviewed now. Will be due in the next patch releases, which I should be able to prepare next week.

**Comment by AndyButland** [comment]
I've prepared patch releases that include a fix to this issue, due to be released on 16th August.

If you'd like early access to it, you can find it for Umbraco 9 and 10 on this NuGet feed:
https://www.myget.org/F/umbracoprereleases/api/v3/index.json

If you add that as an entry in `<packageSources>` within the `NuGet.config`, you should be able to reference the following two packages (which are the ones you need for Umbraco 9):

```
    <PackageReference Include="Umbraco.Deploy.Cloud" Version="9.4.2" />
    <PackageReference Include="Umbraco.Deploy.Forms" Version="9.4.2" />
```

**Comment by ygrave** [comment]
Hi Andy,
Thanks a lot for this patch. We will test it asap. I will let you know if the problem is fixed.
Have a nice day.

**Comment by ygrave** [comment]
Hi @AndyButland ,
We just try to use this version but we cannot find this version on the feed. We have only the version 10.0.3 or 10.0.0 available (see also attachment)!? Do you have for us the right package?
In advance thanks.
Yves.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/33352749/183600010-1ed6207a-99c3-43ee-a97d-01408f1d93b5.png)

**Comment by AndyButland** [comment]
Sorry, it looks like it got removed by our retention rules on that feed (as it's not the latest major).  I've adjusted the rules and re-added it, so you should find it there now.

**Comment by ygrave** [comment]
Hi @AndyButland ,

We deployed this patch and everything is working fine now. Thanks a lot.

Have a nice day.
