### ISSUE TITLE
Decimal value is not transferred correct

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#134]
We have an Umbraco Cloud project using followinng:

Umbraco v10.0.1.1
Forms v10.0.4
Deploy v10.0.2

Locally I have a price using Decimal property editor with value 18500 (no thousand or decimal separators).

![image](https://user-images.githubusercontent.com/2919859/180205683-4fdf9d7c-8ebc-4c18-ba60-463f9e773084.png)

When I transfer the node to Umbraco Cloud, the value is multiplied by 10.

![image](https://user-images.githubusercontent.com/2919859/180205831-e9f89fde-700b-4757-a7cf-9e8f59c3e04f.png)

**Comment by bjarnef** [comment]
We I fix the price on Umbraco Cloud live environment to value 18500 and restore to local environment, it is also transformed to 185000.

**Comment by bjarnef** [comment]
@AndyButland any idea why the decimal value is multiplied by 10 on transfer?

**Comment by AndyButland** [comment]
That does seem odd, and no, no immediate idea I'm afraid.  I've not been able to replicate though.

I'm using a decimal property value set with these settings and the value is transferred as is:

![image](https://user-images.githubusercontent.com/1993459/181742262-ec22244d-a6ff-4d4d-a430-42f5a36bd1cf.png)

Maybe if you have different settings you could share them and I'll try to more closely replicate your setup to see if that reveals anything.

**Comment by bjarnef** [comment]
@AndyButland in this case the configurations are just blank.

![image](https://user-images.githubusercontent.com/2919859/181755234-c81a1ca5-3e2b-423e-bd34-0f1a1b60b6b9.png)

**Comment by bjarnef** [comment]
It's a Umbraco Cloud environment. I can send you and invite if you need to debug this further, but there shouldn't be anything special about this property.

**Comment by AndyButland** [comment]
OK, yes, please do and I'll see if that helps to figure out what's going on.

**Comment by AndyButland** [comment]
Thanks - am still not seeing it though I'm afraid.

I've:

- Cloned and restored.
- Looked at the "Kursus i grammatik" node, where I can see the price was 449500 (both on Cloud and locally).
- Changed it to 4495 and deployed, and it's 4495 on Cloud.
- Put it back to 449500 locally and deployed, and it's 449500 on Cloud.

I guess I'm missing something... can you see what?

**Comment by bjarnef** [comment]
Strange, when I restore the node "Kursus i grammatik" which had a price value on 449500 it is restored as 4495000 on my local environment.

I wonder if there is any culture/language specific logic in the transfer/restore process?

**Comment by AndyButland** [comment]
Yes, I was thinking it must be something related to that.  Examining the code in Deploy though it does look like we are using invariant culture for the transfer.

However, I've just tried adding this into the `Startup.cs` of your project (in the `Configure` method):

```
  var cultureInfo = new CultureInfo("da-DK");
  
  CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
  CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
```

And sure enough, I see the problem now on a restore.

Will dig further...

**Comment by bjarnef** [comment]
@AndyButland that was what I was thinking as well to configure a default language in `Startup.cs`

I think you can reproduce as well by setting Danish as culture (either a specific hostname or inherit from Danish).

![image](https://user-images.githubusercontent.com/2919859/182105963-79363d7a-d757-4019-828f-404c9f0dd00a.png)

**Comment by AndyButland** [comment]
I've raised an issue on the CMS tracker for this (linked above).  As you'll see if you have a read, I can replicate it there by switching culture which is the root of the issue.  I haven't figured out the solution, but at least there's visibility of the issue on that tracker now.

I believe the issue only occurs when using SQLite locally, so if you are on Windows and can switch to SQLExpress that would be a workaround for the issue.

**Comment by bjarnef** [comment]
@AndyButland thanks for investigating this. I thought this project was using LocalDB but it seems to use SQLite. It was another Umbraco Cloud project upgraded to Umbraco 10 where I configured `"PreferLocalDbConnectionString": true` so it makes sense why I didn't noticed in that project.

**Comment by AndyButland** [comment]
The related issue raised on the CMS tracker has now been closed, and I can see a fix is due in the next minor releases of Umbraco 10 and 11.  So will close this issue now.
