### ISSUE TITLE
Make `RegisterTransferEntityType` action parameter `matchesNodeId` accept a `HttpContext` argument

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco.Deploy.Issues#141]
Currently the API to the `matchesNodeId` action parameter of the `RegisterTransferEntityType` API is of the signature `Func<string, bool>` which based on the docs here https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Extending/#backoffice-integrated-transfers assumes that the ID paremeter is going to be fudged to hold extra information. In Vendr however we don't fudge the ID, and instead when we render our tree nodes we merge in some extra parameters into the querystring which we can then use to negotiate the current context.

Unfortunately as the `matchesNodeId` only accepts the ID we don't have access to this extra context to be able to work out if the item is indeed the right match. Ideally the `matchesNodeId` action signature could be changed (or better, to maintain backwards compat added as another signature option) to `Func<string, HttpContext, bool>` and so as well as the nodeId the current `HttpContext` is also passed.

This would be inline with the next param `tryParseEntityIdFromNodeId` which accepts a string nodeId and the `HttpContext` for the purposes of parsing the ID out so it must already be known.

I'm currently trying a workaround to the use then unrecommended `StaticServiceProvider` in order to resolve the current `HttpContext` but you can understand why I would prefer not to do that.

**Comment by AndyButland** [comment]
This has been added for Deploy 11 as it's a breaking change to the method signature.  If it's useful in earlier versions we can look at back-porting, so long as we can find a way to avoid the breaking change.
