### ISSUE TITLE
Deploy does not run on start up after revision changes outside of Umbraco

### ISSUE THREAD

**Issue by TQ-Benji** [umbraco/Umbraco.Deploy.Issues#142]
When a new revision file is added or an existing file is changed externally from Umbraco Backoffice. eg from a git pull from another developer. Deploy does not run and apply those changes.

Reproduction
------------

### Bug summary

Video showing the issue. 
In this case. file is edited locally but if the file change via git that would be the same.
https://recordit.co/ObDh5i8VT4

### Specifics

Umbraco 10.3.2
Deploy 10.1.1

### Steps to reproduce

Make change to any revision file eg remove a AllowedChildContentTypes Guid from a doc type permissions
Delete the deploy log and deploy status file
Start the site up
Check revisions have been applied

### Expected result

Deploy log and status file created during site startup indicating that deploy ran
The change made in "steps to reproduce" is made. eg doc type removed is no longer available under child node permission

### Actual result

Deploy log and status file remain missing
Change made to revision file. eg doc type still existing as an allowed child type for that node

**Comment by AndyButland** [comment]
Just following up on this, could I ask if you are using Umbraco Cloud, or Umbraco Deploy On-Premise please?  Thanks.

**Comment by TQ-Benji** [comment]
Hi, @AndyButland I'm using Umbraco Cloud

**Comment by AndyButland** [comment]
OK, then it might be worth just having a look over the documentation [here](https://docs.umbraco.com/umbraco-cloud/set-up/working-locally#renaming-the-project-files-and-folders), particularly the part about the git hook, which should be in place with Umbraco Cloud to give the behaviour you were expecting.  It might not be if you have renamed the default project name or folder structure.

**Comment by AndyButland** [comment]
Will close this one given no further activity, and that the feature requested should be in place automatically when working with Umbraco Cloud. If you've followed the docs linked above on this and are still having trouble, please feel free to re-open.
