### ISSUE TITLE
Umbraco.MultipleTextString is not transferred correctly

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Deploy.Issues#143]
When transferring a property using the `Umbraco.MultipleTextstring` propertyeditor, the values are squashed together in a single value.

Reproduction (updated versions)
------------

**Umbraco version: 10.2.1**

**Deploy version: 10.0.3**

### Steps to reproduce

Clone an environment to local (A) and start the site

- Create a document type with a property of type "Repeatable textstrings"
- Create a Content item from the doctype
- Add the values "First" and "Second" to the property on the content item
- Queue the content item for transfer
- Transfer the item to the next environment (B)
- Observe that the content item on the environment (B) only has a single value "FirstSecond" in the property

### Expected result

The content item should have the same two values in the environment (B) as on local (A)

**Comment by AndyButland** [comment]
Hi @greystate - I've been trying to replicate this this morning, but have not been able to I'm afraid.  I see the expected result.

I'm using the latest Deploy version, 10.1.1.  Are you on the same please?

**Comment by greystate** [comment]
Ah - thanks @AndyButland

I can see this is using `Deploy 10.0.3` - so have probably been fixed already.

I'll try to get it upgraded soon then, and report back 👍

**Comment by greystate** [comment]
Hi again,

So I've now upgraded to Umbraco v10.3.2 and Deploy v10.1.2 and made sure the local clone have been built using the new versions as well.

I added a few more values to the MultipleTextstrings property and transferred it to the Development environment. They're still just beeing slammed into the first textbox...

In the log that's running on the local server, I can see that the value is transferred as:

```json
"propertyAlias": {
	"": {
		"Value": "sValue1\nValue2\nValue3\nValue4\nValue5",
		"Segments": []
	}
}
```

So whether it's the receiver that doesn't parse the newlines correctly, or it's the sender not "packing" the right JSON, I don't know...

**Comment by AndyButland** [comment]
Mac v Windows maybe?  Will have a look further next week, but I suspect it's something about newlines as you suggest.

**Comment by greystate** [comment]
That's a possibility - wouldn't be the first time in history newlines behaved differently on a Mac vs. a PC 😁

**Comment by greystate** [comment]
Definitely is a Mac vs. PC thing - just did a transfer from DEV to LIVE where everything went over correctly (which I assume all happens on PCs somewhere in the cloud 😆 )

**Comment by ronaldbarendse** [comment]
@greystate Thanks for reporting this issue! This is indeed an issue specific to the `Umbraco.MultipleTextstring` and it's use of `Environment.NewLine` to join/split the multiple text string values.

Although we can fix this issue within Deploy by normalizing the newlines before transferring the content on the source environment and then changing it to use the `Environment.NewLine` of the destination environment again, that would be more of a workaround.

Instead, I've created a fix for the CMS (see PR https://github.com/umbraco/Umbraco-CMS/pull/13569) that ensures existing data can be correctly parsed (split) and uses a consistent, normalized, newline when saving the (joined) value to the database.

**Comment by greystate** [comment]
That's great Ronald 🙌

**Comment by AndyButland** [comment]
I'll close this issue now given the related fix in the CMS has been tested and merged in.  It's due in CMS release 10.4 and 11.1.
