### ISSUE TITLE
Tree picker in partial restore shows caret for nodes without children

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#146]
When using partial restore I noticed the tree picker shows caret for all nodes also nodes without children.

![image](https://user-images.githubusercontent.com/2919859/204472855-1d421c1c-dc97-4695-99cd-1d73a911fe97.png)

When trying to expand these, the carets are gone.

![image](https://user-images.githubusercontent.com/2919859/204473194-909f1e9a-3371-4514-9cf8-3d7deff4fdf8.png)

Not sure it is a bug in Umbraco core or Deploy, but haven't noticed the same issue with core tree picker.

Umbraco v10.3.2
Deploy v10.1.2

**Comment by AndyButland** [comment]
Thanks for reporting this one, I can see why we aren't rendering this correctly and will have this fixed in the next patch release.
