### ISSUE TITLE
Partial restore seems to be slow

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#148]
On a Umbraco Cloud project when we on local do a partial restore and only select a single tree node, it seems to be quite slow.

I also tried on root level with a node with tree child nodes, but not dependencies to other nodes, which was running for a while.
It seems sometimes to be faster when selecting not to include children.. and restore from that parent node later.

We have an archive with 30K nodes, not sure if that affect the process in any way? I would not expect to since it is not the content selected to restore nor this content has dependencies to any of these 30K nodes.

However with a simple partial restore of a few nodes, we often end up with this error "The remote API did not return application/json content.": https://github.com/umbraco/Umbraco.Deploy.Issues/issues/128

Umbraco v10.3.2
Deploy v10.1.2

**Comment by AndyButland** [comment]
Please see some updates related to this in [this comment](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/128#issuecomment-1425612448) on another issue.

I'll close this as the updates in the releases indicated will address and improve this situation.  Of course if having updated and if not finding a resolution please feel free to re-open or create a new issue.
