### ISSUE TITLE
IgnoreBrokenDependencies setting is missing

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Deploy.Issues#151]
The [docs](https://docs.umbraco.com/umbraco-deploy/deploy-settings#ignorebrokendependencies) and various forum posts / issues point to `IgnoreBrokenDependencies` being a valid setting. However this no longer seems to be the case...

This option also shows in the "Deploy Management" backoffice dashboard, but is always `false`. Had me going mad trying to work out why my changes weren't applying!

The `IgnoreBrokenDependenciesBehavior` flag was introduced as part of #81 for v8 & v9 and so `IgnoreBrokenDependencies` was seemingly dropped sometime after that. I would never check the source... but the property no longer exists in the `DeploySettings` configuration class, and remains in the `DeployManagementDashboardController.ConfigurationModel` class (just isn't set)...

Checked against Deploy v10.1.2.

Looks like the docs + backoffice + maybe a few classes need a clean up 🙂

**Comment by AndyButland** [comment]
Thanks for the report @callumbwhyte and apologies for this not being clear and wasting you some time.  As you say [this was tidied up in Deploy 10](https://docs.umbraco.com/umbraco-deploy/upgrades/version-specific#configuration), as the `IgnoreBrokenDependenciesBehavior enum` is sufficient without the boolean option as well.  I'm fairly sure we did also remove it from the dashboard, but I think it must have come back in a dodgy merge at some point.

Will remove for the next patch release.

Have also created a PR to update the docs to what we have for Deploy 10 (with a reference to to what existed for Deploy 9).
