### ISSUE TITLE
Form field "contains sensitive data" property is not transferred between environments

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Deploy.Issues#154]
When transferring a form between environments, the value of the `ContainsSensitiveData` field is lost and defaults to `false`.

Affects Deploy 4 (for Forms 8) and up..

**Comment by RGV2ZWxvcGVy** [comment]
@AndyButland Will there be a new minor version of Umbraco Deploy available soon that contains this fix?

**Comment by AndyButland** [comment]
There will yes.  Sorry, I realise I forgot to add the labels.  Done now.
