### ISSUE TITLE
Workflow flag "Include Sensitive Data" not transferred properly

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [umbraco/Umbraco.Deploy.Issues#159]
When transferring a form that has the "Include Sensitive Data" toggle set to true within a workflow, the value is lost and defaults to false. Related to: #154 but this issue specifically targets the workflow.

Using Umbraco 10.4.0, and Umbraco Deploy 10.1.3 with Umbraco Forms 10.2.3

Reproduction
------------

1. Create a form
2. Add a send email workflow
3. Set the Include Sensitive Data toggle to true
4. Submit the workflow, and save the form
5. Transfer the form to the target environment
6. Check out the workflow on the target environment

![image](https://user-images.githubusercontent.com/105918931/218787999-c19e01d9-54a3-4dfa-992c-ace3bf012000.png)

**Comment by AndyButland** [comment]
Thanks, a similar issue to the other one you raised.  We'll include this in the next releases for Deploy.

**Comment by RGV2ZWxvcGVy** [comment]
@AndyButland Awesome, thanks!

**Comment by RGV2ZWxvcGVy** [comment]
@AndyButland Is there a date yet for the 10.1.4 release? I tried to test with the prerelease via: https://www.myget.org/F/umbraconightly/api/v3/index.json but Umbraco Cloud won't let me deploy prerelease versions.

**Comment by AndyButland** [comment]
We're aiming for 24th March for the next Deploy patch releases.
