### ISSUE TITLE
Sort on column "Is Up To Date"

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#165]
In Umbraco Deploy v10.1.2 I noticed in Deploy dashboard in Settings section, it is possible to sort columns by **Exists In Umbraco** and **File Exists** ...  but not on column **Is Up To Date**.

It would be useful to sort on as well :)

**Comment by AndyButland** [comment]
Makes sense, I'm not sure why we originally left that column out.  We'll include it in the next release.
