### ISSUE TITLE
Redirect URL management redirects are not being transfered from one environment to another

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco.Deploy.Issues#170]
Deploy 4.7.4/11.1.2

Seems to be related to this thread: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/35#issuecomment-1025603579  

When renaming/moving a content node in the content tree, a redirect is created.
When transferring the content these redirects should also be transferred if the content exists in the next environment.

However, it doesn't do it.

In this specific case with Heartcore projects, on older created Heartcore projects (even though versions are the same as newer ones)

One thing we noticed is that they have parent nodes that do not vary by culture, with vary by culture child nodes.
Whenever you transfer these it won't add a value to the culture for the redirect which is why the redirect is transferred wrong and looks like this 

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/83580347/a4aa284e-74d8-42b8-9095-703d0b5dbe6e)

Out of curiosity, I tested this behavior on my v11 test project, I encounter a different behavior completely.
None of my redirects are transferred at all, there.

In the Deploy codebase, we indeed don't transfer redirects, but there is logic to ensure if you have existing content on the remote/destination environment, it will create redirects when the content segment changes or it's moved.

### Specifics
Here is a video to showcase the problem.
https://github.com/umbraco/Umbraco.Deploy.Issues/assets/83580347/e3bb2eab-8a36-45d5-b43d-fd902cad90c7

### Steps to reproduce
1. Created a Umbraco Cloud project with 2 environments
2. Created some document types with a parent that doesn't vary by culture and children that vary by culture
3. Created some content on the dev environment & transferred it over to Live
4. Then I renamed/moved around content trees - to create some redirects in the Redirect URL management
5. Transferred all the content, and got not redirects.

### Expected result
Expected to get all the redirects in the Live environment.

### Actual result
Didn't get any redirects

**Comment by ronaldbarendse** [comment]
This should now be fixed in the latest Deploy versions (4.8.2, 10.2.3, 11.1.3 and 12.0.1, no patch for v9 because that is EOL), as mentioned in the [release notes](https://docs.umbraco.com/umbraco-deploy/release-notes) as: _Corrected logic for creating redirects on content deployment for variant content_.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/umbraco-cloud-301-redirects/6330/2
