### ISSUE TITLE
Rename of folder doesn't trigger schema change

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#171]
I noticed while I was restructuring some document type folders I renamed a folder "Grid" to "Layouts", but after restore content I got mismatch, because the folder name was "Layouts" on local environment, but still "Grid" on live environment.

I tried renaming the folder locally to something else, but it didn't triggered a schema change.
However creating a new folder does trigger a schema change.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/113aa7df-8105-4269-bba8-f7fdcddb52e0)

Renaming this folder from "Test" to "Test 2" didn't have any effect on the uda-file, the name property still contain "Test".

Deletion of the folder removed the uda-file as well.

For now any renamed folder need to be renamed on each environment (or perhaps rename manually in the uda-file works as well).

Furthermore it doesn't seem Deploy dashboard list comparison of folders (document type and datatype folders/containers) in case of any mismatches.

Umbraco 11.4.1
Deploy 11.1.2

---
_This item has been added to our backlog [AB#31244](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31244)_

**Comment by bjarnef** [comment]
Renaming folder on each environment wasn't enough and still caused mismatch on restore.
I guess it still compare the uda-files.

I had to updated the uda-file manually and push this change. After that I could restore successfully.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/8f1716e4-8eab-466d-910e-d0dc7f288da8)

**Comment by bjarnef** [comment]
@AndyButland the folder has been updated on live environment.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/b8cbbd5d-981c-47ed-bbad-d6e436c0275e)

and the uda-file is identical with local version.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/5388e088-dfdd-4216-a2e2-3f63201a268e)

However when restoring some location nodes it fails with mismatch (but only the one with grid content using Block Grid editor).

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/ca19b9aa-ccef-40ce-8e32-e8c07ffb3467)


```
9c9fa37a - Executing, 10% - Get remote session
9c9fa37a - Executing, 20% - Create manifest on source
9c9fa37a - Executing, 25% - Review manifest on target
9c9fa37a - Executing, 80% - Exception!
9c9fa37a - Executing, 80% - Abort remote session
9c9fa37a - Executing, 80% - Restore caches and indexes
9c9fa37a - Failed, 80% - Total time 00:00:02.761.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Umbraco.Deploy.Core.Exceptions.RestoreSchemaMismatchException: Schema mismatch between environments. See 'Mismatches' for details.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Core.Exceptions.RestoreSchemaMismatchException: Schema mismatch between environments. See 'Mismatches' for details.
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.ValidateManifest(Manifest manifest, ValidationContext validationContext)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetPartialRestoreWorkItem.Proceed()
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetPartialRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetPartialRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetPartialRestoreWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
```

**Comment by bjarnef** [comment]
On live environment it has a location node "Denmark" with grid content, where it use the "One Column Layout" section block.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/5e325bca-56d1-463c-8d44-35e52c988d0b)

**Comment by bjarnef** [comment]
Okay, it turns out the clicking the "clear cached signature" button fixed the part and it restored the node successfully.

However it is still and issues that renaming folders doesn't trigget a schema change.

**Comment by AndyButland** [comment]
It looks like we are missing handling the `EntityContainerRenamedNotification` and are only dealing with the `EntityContainerSavedNotification`.  That explains the behaviour you see and I can see in testing a fix that by also handling the former we get the `.uda` file updating as expected.
