### ISSUE TITLE
Queue for transfer on listView (list view)

### ISSUE THREAD

**Issue by AntonioRamos** [umbraco/Umbraco.Deploy.Issues#172]
### Issue description

Allow Queue for transfer for multiple selected nodes on listView. This will allow a simplier transfer between environments from pre-selected items on listView.

**Comment by AndyButland** [comment]
This would be nice I agree, but unfortunately it's one I think needs to wait for the new backoffice where we should have more extension points here for adding custom buttons here.  I'll close this as it's already tracked under #140.
