### ISSUE TITLE
Image alt text not transferred. Deploy bug issue!

### ISSUE THREAD

**Issue by Jay-1975** [umbraco/Umbraco.Deploy.Issues#174]
A brief description of the issue goes here.

Issue with alt text data not deploying across dev->stage->Live environments. 
Anders from Umbraco support has tested our issue with the same result as we have.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Open up image in content
![pic01](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/141845555/b8619230-62d0-4f9f-a261-e742ef5c19b3)
, Edit image within content page to include alt text. Save and Publish and deploy changes to
Staging then Live from Dev. Text in the alt text field is not transferred between environments.

### Specifics

Occurs in Dev and Staging Environments. There is no error, the text simply doesn't transfer over to the next environment.

### Steps to reproduce

- Log in to dev-champ.euwest01.umbraco.io/umbraco
- Open any content page with image.
- Edit image within content, change blank alt text to include some text.
- Save and Publish.
- Transfer content page with changes to next environment up (which will be stage-champ.euwest01.umbraco.io/umbraco

### Expected result

Expect to see text from image in content page transferred from dev to stage .

### Actual result

Alt text data not showing in the next environment (in this case staging). Also, doing the same from staging to Live
produces the same result (no text in alt text).

---
_This item has been added to our backlog [AB#31871](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31871)_

**Comment by Jay-1975** [comment]
Just heard back from Montreal Team:

OK. I synced the media first.

Checked. alt text not transferred.

I synced the content block afterwards.

Checked. Same results.

as expected, alt text not transferred between servers

**Comment by Jay-1975** [comment]
the JSON data transferred/saved does not appear to mirror the source

**Comment by Jay-1975** [comment]
It is utilizing the image cropper and the Image media type. 

We are using Umbraco 10.5.0 and Deploy 10.2.3

![pic01](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/141845555/92366ae4-d5c6-40f4-a6ad-e5ff9dd647da)

![pic01](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/141845555/c7e4f827-a266-4542-8217-bed0e6c20311)

**Comment by AndyButland** [comment]
Thanks, I've been able to replicate now.  This issue occurs when using the legacy grid, and here the alt text/caption is set not on the media item but as part of the grid content (so the comment I made above about transferring of media isn't relevant).

**Comment by Jay-1975** [comment]
So, based on the fact we are currently using the legacy grid there is no other way around this issue other than recreating all the legacy grids to block grid? I'll get back to you if I get anything back from our Ottawa team. Thanks Andy.

**Comment by AndyButland** [comment]
No, not at all - we still support the legacy grid with Deploy.  I've been looking into it this morning and a fix will be available with the next patch release we make available for Deploy.

**Comment by Jay-1975** [comment]
Thanks for looking into this Andy. I have let the Ottawa team know and see if they have any other questions regarding this issue. A question I have is when can we expect to see a patch release for Deploy?

**Comment by AndyButland** [comment]
It's not scheduled yet.  We just released the last patch so this is the first item for the next one, but I'd expect in the next few weeks.

**Comment by Jay-1975** [comment]
Sounds good! Thanks again for your help on this Andy. Unfortunately, we were in a spot where we'd have to recreate all of our Legacy grids to block grid and it would have been a lot of tedious work, especially as we are set to launch the Live site around September 12th. At least we know we will eventually get the functionality needed to move forward.

**Comment by AndyButland** [comment]
Understood.  Yes, one day I imagine you'll have that migration task as it is the intention that block grid supersedes the existing grid... but certainly no need to do it for this issue.

**Comment by Jay-1975** [comment]
Thanks Andy, I'll close the issue now and we will keep our eye out for the Deploy patch.

**Comment by AndyButland** [comment]
Thanks, but just to follow usual process, I'll keep it open until the related PR is reviewed and merged... then I'll close and label with the release numbers.

**Comment by Jay-1975** [comment]
I see, I wasn't aware of the process.
