### ISSUE TITLE
Dictionary item translations are sorted different when extracted

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#175]
On a Umbraco Cloud project I have some issues with changes in dictionary items as schema data when pushing/pulling between local and live environment.

E.g. when pulling latest changes from Umbraco Cloud everything is fine, but when I go to Deploy dashboard and click button at "Update Umbraco Schema From Data Files" I have changes to commit, because the order/sorting of translations in the dictionary item has changed.

Of left the original schema data, on right after extraction.

![BCompare_ahfqHvT7Na](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/a65ba3d0-7806-4b6c-a99b-5b9adaf37357)

If I push these changes then later I have some changes from Umbraco Cloud to pull, probably because it sort/serialize the translation items different than on my local environment.

Could we e.g. sort the items alphabetically by `LanguageIsoCode` on serialization, so they are always the same? Or by language name, so the items are sorted just like in backoffice?

![chrome_BU3ZuBlOfC](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/aabdbed0-cd71-44c8-bad8-462aac02f2bc)

Umbraco Deploy 12.0.1
Umbraco 12.0.1

---
_This item has been added to our backlog [AB#31977](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31977)_

**Comment by AndyButland** [comment]
These will be serialized with ordered translations by ISO code from the next releases.
