### ISSUE TITLE
Deploying of User as Content should be avoided

### ISSUE THREAD

**Issue by meyntony** [umbraco/Umbraco.Deploy.Issues#180]
We have noticed that if Umbraco content has a property of the datatype UserPicker, the content transferred  may have wrong information after a deploy, since Deploy cannot be used to deploy Users between environments, it should ignore this information when its transferred.  

**Steps to Reproduce:**
- Add a user picker to a document type
- Select a user when editing the content based on the document type
- Transfer the content

**Expected Result:**

- No User value is transferred and the user picker is empty (even if the ID of the user selected in one environment exists in the other).

**Actual Result:**

- User value is sometimes transferred and the user picker may have a value if the target environment has a User with the same ID as the source environment

**Comment by AndyButland** [comment]
We'll have a resolution for this in the next patch releases that should work with most scenarios.  Users are maintained separately on each environment, so there's no ID that unambiguously relates two users between two environments.

With the new behaviour we use the username to see if we can find a user that matches in the target environment, and if so, assign that to the user picker field.  If one is not found, an empty value is stored.

**Comment by meyntony** [comment]
Is this the same behavior if the `MemberPicker` was used too?

**Comment by AndyButland** [comment]
No, not yet, but we'll consider that too.  That one is a little different as it is possible to transfer members between environments, so they can be matched up.  But if you click through to the PR you'll see some discussion about things we need to handle there.
