### ISSUE TITLE
Content Templates are Partially Deployed - 12.0.2

### ISSUE THREAD

**Issue by paulsterling** [umbraco/Umbraco.Deploy.Issues#182]
Using an Umbraco Cloud Project with versions:
CMS: 12.1.2
Deploy: 12.0.2

### Bug summary
When deploying a Content Template from Local > Live only the template structure is deployed. All properties values are missing once deployed to Live. HQ support was also able to reproduce this issue using the standard Starter Kit and the below repro steps.

### Reproduction
------------
1. In the Local clone of the Cloud Project
2. Create a Content Template from a Content Node's Action menu (Create Content Template)
3. Navigate to Settings > Content Template > Your Content Template
4. Update some of the values in the Content Template and Save
5. Right-click the Content Template and select Queue for transfer
6. Open the Transfer queue and select Transfer to Live
7. Login to the backoffice of the Live Cloud Project
8. Navigate to Settings > Content Template > Your Content Template
9. Note that all property values are missing

### Specifics
No error is displayed or present in the logs. The deployment log indicates the deployment is complete.
Both plain (eg, textbox properties) and more complex (eg, blocklist properties) are missing values on Live.

Using an Umbraco Cloud Project with versions:
CMS: 12.1.2
Deploy: 12.0.2

## Content Template on Local
![local](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1653490/56e64022-42e7-4bee-bd06-304c01118552)

## Content Template on Live
![live](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1653490/0f6d5b38-cdce-467e-8ceb-d0be83dacd8f)

---
_This item has been added to our backlog [AB#33307](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33307)_

**Comment by AndyButland** [comment]
Looks like this was a regression caused in the previous patch release where we looked to resolve an ordering issue with how different entities were processed. and omitted part of the necessary update.  We'll get this sorted in the next patch release, that we'll aim to get out next Tuesday.
