### ISSUE TITLE
Improve documentation about cache refresh

### ISSUE THREAD

**Issue by Abrissirba** [umbraco/Umbraco.Deploy.Issues#183]
We have a custom cache mechanism in our umbraco web. We have a handler for the ContentPublishedNotification that will clear the cache for that page. However, this notification does not seem to be published when doing a deploy and therefore our cache is not updated. 

Reading the documentation I found this, https://docs.umbraco.com/umbraco-deploy/deploy-settings#suppresscacherefreshernotifications. It just says cache refresher notifications are fired but it is not clear which ones. Is it the "normal" ones or are there any custom notifications for umbraco deploy? What I would like to know is which content nodes that has been updated in the deploy.

---
_This item has been added to our backlog [AB#33496](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33496)_

**Comment by AndyButland** [comment]
The linked PR has been merged now, so I'll close this issue.
