### ISSUE TITLE
Transferring content with language variants enabled - items are not published/fields are empty

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Deploy.Issues#193]
When you try to transfer content and have more than one culture enabled, it seems Deploy gets confused and transfers the content structure - but most, if not all fields on language variant doctypes are empty.

Reproduction
------------

Create a new project on UmbCloud.
This should work with any kind of content transfer as far as I can tell, so you can spin up a local environment and push to Live or go from Dev to Live.
Create any content structure you like, make sure to enable vary by culture on doctypes and some fields, add content, then try to push content to your cloud environment.

Umbraco 13.0.3
Forms 13.0.0
Deploy 13.0.1

I uploaded a video recreation of the issue.

https://github.com/umbraco/Umbraco.Deploy.Issues/assets/56038614/6a9812f4-a4fa-4e1d-9b1b-1f8ead694b15

---
_This item has been added to our backlog AB#36352_

**Comment by rhealefever** [comment]
I ran into this issue back in December, but my reproduction steps didn't include a starter kit with language variants. Great sleuthing! Can confirm I've also run into this.

**Comment by AndyButland** [comment]
I've been able to replicate the issue here and we'll ensure it is resolved in the next round of patch releases, due for Cloud release next week.

**Comment by jattwood** [comment]
We are experiencing this issue on Umbraco cloud 11. But only when using delayed/scheduled publishing. Normal multi-language content transfers as expected, but as soon as you set a later publish date on a content item, the node is transferred completely empty (other than a node name). When the scheduled publish time arrives, the publish fails based on any document type mandatory property validation rules failing. We are using Deploy: 11.1.7
