### ISSUE TITLE
Invariant fields not transferring on multilingual site

### ISSUE THREAD

**Issue by mpontin** [umbraco/Umbraco.Deploy.Issues#194]
#### Overview
When transferring content changes from one environment to another on a multilingual (variant) site, fields that aren't varied by culture do not get transferred.

#### Details
We have an Umbraco 13, Umbraco Cloud hosted site with 2 languages (EN, IT). 
Multiple templates across the site have invariant fields as well as variant fields. 
When trying to push changes to those pages from the development environment to the live environment only the variant field values are transferred. 

There is no error message given, everything initially looks to have worked, but manually checking the content in the CMS on the live environment shows that the content hasn't transferred.

Using the compare tool shows that there is a difference between the two environments.

Have tested with mandatory and non-mandatory fields and with multiple data types, including Media Picker, Toggle and Date Picker.

**Comment by AndyButland** [comment]
Thanks for the report - we got a report of this earlier in the week so I'll close this as it duplicates https://github.com/umbraco/Umbraco.Deploy.Issues/issues/193.

It will be fixed in the next patch release, which will be auto-upgraded on Umbraco Cloud next Tuesday and released to NuGet today.
