### ISSUE TITLE
Nodes not published after content transfer from a list view

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [umbraco/Umbraco.Deploy.Issues#195]
When transferring published child nodes within a list view, the child nodes are not published on the target environment.
Using Umbraco Cloud 10.8.3 and Umbraco Deploy 10.3.2.

Reproduction
------------
1. Create a new node that is configured to use a list view.
2. Create one or more child nodes, and publish them.
3. Transfer the parent node that uses the list view to the target environment.
4. Transfer one or more child nodes to the target environment.

### Source environment
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/105918931/1ea5d401-5a11-49d8-a261-7e0388372f9d)

### Target environment
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/105918931/1f443437-6ad2-40f8-98ce-dc8c1a5164b2)

The child nodes are still in draft when they should actually inherit the published state from the source environment.
I am not sure if the behaviour is exactly the same when using a default list view or custom list view. In this example I used a custom list view.

**Comment by AndyButland** [comment]
Good to hear that's what it is (though apologies for the regression and inconvenience).  You should find a patch released to NuGet before the end of this week, which will be auto-upgraded on Cloud next Tuesday.
