### ISSUE TITLE
Appearance for property label not being deployed between environments

### ISSUE THREAD

**Issue by tcmorris** [umbraco/Umbraco.Deploy.Issues#2]
There is an option when editing a property for the label to appear above the property editor.

![image](https://user-images.githubusercontent.com/2123628/110502355-0a1ccd00-80f3-11eb-93a5-8d0ad7645d3a.png)

Unfortunately, this doesn't appear to be persisted between environments. Looking at the .uda files in the data/revision folder, there is no data associated with this option.

In the example below, both of these have the 'Label above (full width)' option ticked in the property settings. 

![image](https://user-images.githubusercontent.com/2123628/110502753-6384fc00-80f3-11eb-8a62-c951e362e401.png)

Reproduction
------------

### Bug summary

'Label above (full width)' option is not deployed between environments.

### Specifics

Umbraco 8.11.1
Deploy 3.5.4

### Steps to reproduce

1. Create doc type
2. Create new property
3. Add required info for property
4. Tick the 'Label above (full width)' option
5. Commit changes of the .uda files
6. Deploy to another environment
7. The value is not updated

### Expected result

Would expect the 'Label above (full width)' option to persist between environments.

### Actual result

Have to tick this option manually on each environment instead.

**Comment by tcmorris** [comment]
Just wanted to confirm that this is all working good here. Thanks for fixing 👍

**Comment by AndyButland** [comment]
Thanks for confirming @tcmorris - good to hear.
