### ISSUE TITLE
Set a deploy-progress  marker file when running echo > deploy

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco.Deploy.Issues#20]
When running echo > deploy from commandline it could take quite some time for larger sites.
Currently there is no feedback provided at all until the 'deploy complete' markerfile is set.

It would be nice to have a deploy-progress indication.
Actually... didn't we have this before?

**Comment by AndyButland** [comment]
I believe we can close this one.  With the new management dashboard introduced in 4.1.0 under _Settings > Deploy_, there will be a means of viewing the status of the latest operaton, which if it's still in progress will be listed as "Deployment operation in progress".
