### ISSUE TITLE
Empty message if trying content transfer while set cached signatures is running

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#202]
If one go to Deploy dashboard in Settings section and click "Set Cached Signatures"

and then go back to content at do a content transfer while still in progress, then an empty message will show up.

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/d6bd18c6-228b-4400-aaa9-8c97327205fe)

The message is a bit misleading, because the is no content transfer yet, it is only the cached signatures being prepared.
At this state the actual content is not transferred yet.

Umbraco 13.0.3
Forms 13.0.1
Deploy 13.0.3

---
_This item has been added to our backlog AB#37030_

**Comment by AndyButland** [comment]
These UX improvements will be part of the next round of patch releases.
