### ISSUE TITLE
Option to export dictionary items

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco.Deploy.Issues#207]
As Deploy and it's Export/Import feature and it's migrators is being "marketed" as a tool for migrating Umbraco sites from old to new versions, I think it would make sense that the user is given the option of exporting dictionary items as well. 

I love the new export/import feature, but I genuinely though something was wrong when none of the sites dictionary items was migrated using the export/import feature. 

Right now, you would have to copy the .uda files manually, from the old site to the new site. Or export and import them one at a time. It would be lovely if you had the option to migrate everything backoffice with a single click.

**Comment by AndyButland** [comment]
Just to explain why it currently works the way it does... "Workspace export" will find all the things the editor could content transfer via the backoffice, and include them in the export; along with, if selected, any schema items that are related to them.

So if you are deploying dictionary items as schema, not via the backoffice, they aren't included in the set of "content" items to export.  And as dictionary items aren't dependent on content - as a hard dependency in the way e.g. document type are - they don't get included either in the related schema. 

If dictionary items are configured to be deployed as content, they are included in a workspace export.  So if you are looking to do a one-off migration task, it might be you can just switch, even if temporarily, to that configuration.

---

What might still be valuable and a good idea though is to have some option to export all schema, independent of any reference to content.  And that would include dictionary items.  So keeping this open for further consideration.

**Comment by ronaldbarendse** [comment]
Hi Andreas! We've added a new 'Include all schema' option to the workspace/environment export in Deploy 13.3, 14.2 and 15.0:

![Include all schema](https://github.com/user-attachments/assets/bf5d612c-b550-45e8-a765-877e5b186cb4)

This will include all schema, regardless of whether it is in use by any content, which will therefore now include all dictionary items 💪🏻
