### ISSUE TITLE
Auto transfer about-to-trash content

### ISSUE THREAD

**Issue by SOTFB** [umbraco/Umbraco.Deploy.Issues#215]
As a dedicated user and enthusiast of Umbraco, I wanted to bring to your attention a feature request that I believe could enhance the efficiency and functionality of the platform: the ability to transfer trashed content directly to the production environment.

Currently, Umbraco's Trash Bin feature serves as a safety net for accidental deletions or content that may need to be revisited later - in the happy case scenarios.
However, I believe there's an opportunity to improve the content management process by allowing trashed content to be seamlessly transferred to the production environment.

Imagine this scenario:
You're working in the staging environment, seeing the need for previously deleted content. However, either you are a bit absent-minded and instead accidentally deletes it from the Trash Bin, or even worse, your colleague had emptied the entire bin the day before - this critical piece of content you required, now completely lost.
With the proposed feature, this situation could be remedied by enabling trashed content to be *automatically* transferred to production before the deletion, providing users true peace of mind and reliability with Umbraco.

Furthermore, this feature could streamline the workflow by allowing users to restore trashed content without additional permissions. It would save time and resources, empowering users to focus on content creation without fear of irreversible deletions, or resort to hassle by reaching out to the already stressed internal second-line support team, such as myself, for no avail.

While I understand implementing this feature may require careful consideration and resources, I believe the benefits to Umbraco users would be significant. It would enhance user experience and demonstrate Umbraco's commitment to innovation.

Thank you!

Warm regards
S

**Comment by AndyButland** [comment]
Thanks for the suggestion @SOTFB, but I'm not sure this will be appropriate to add as a feature to Dep;loy.  It seems a counter-intuitive and perhaps dangerous behaviour to have deleted content automatically deployed to production and wouldn't be what most people would expect.  

There is a `ContentMovingToRecycleBinNotification` built into Umbraco, so if you did need more protection than is already built-in two-level delete, perhaps you could hook into that to do something.

**Comment by SOTFB** [comment]
;-)
