### ISSUE TITLE
Broken data types on cloud but functional locally

### ISSUE THREAD

**Issue by simonbusborg** [umbraco/Umbraco.Deploy.Issues#221]
### Description

When creating a data type and attaching it to a doctype, it will fail to display the datatype upon commiting it from a local environment to the cloud environment.

**Local**
<img width="1912" alt="Screenshot 2024-06-03 at 19 24 39" src="https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1101125/dd93fdf0-c060-4aa3-8150-83ac245ce139">
<img width="1912" alt="Screenshot 2024-06-03 at 19 24 50" src="https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1101125/f50d46e2-0f60-45ee-8887-e1813fc9e0ec">

**Live**
<img width="1912" alt="Screenshot 2024-06-03 at 19 24 23" src="https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1101125/bb84668c-1034-46cf-981b-554540a03089">
<img width="1912" alt="Screenshot 2024-06-03 at 19 25 01" src="https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1101125/813d579a-ab87-4075-a188-55e5223b71de">

### Reproduction

Create a datatype (In this case block list editor) and use it in a document type. Commit changes from local to cloud environment. Now, the data types appears blank and is missing settings on the cloud environment

### Specifics
Using Umbraco 14.0.0
<img width="1912" alt="Screenshot 2024-06-03 at 19 20 15" src="https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1101125/21168ccc-b430-41bf-a6e7-e3bde1fae078">

- The issue is not bound to any browser, this is coherent in all browsers.
- No error messages are found
- Data is still available in the database

### Steps to reproduce

To reproduce, create a data type (block list editor), use it in a document type and then commit changes from local to cloud.
I have had this issue with Tags and Block list editor, textstrings and RTE works fine.

### Expected result

The expected result was that the local and cloud solution would be 1:1 and that the data type was displayed correct.

### Actual result

The actual result was missing UI for the data type together with missing settings for the data type on the cloud environment, even though working fine locally.

**Comment by ronaldbarendse** [comment]
Hi Simon, thanks for reporting this! Although we did extensive testing on different release candidates of the CMS, it looks like 14.0.0-rc3 changed the way the data type editor UI is handled during an upgrade (see PR https://github.com/umbraco/Umbraco-CMS/pull/16183). Our example sites that were upgraded to this version all executed the new migration, so all had the editor UI alias populated and I didn't re-test a deployment on an empty environment after this upgrade 😓 I also doesn't help that some editor do work as expected, but only some don't...

Anyway, we'll a fix ready that will be part of the 14.0.1 patch that we plan to release this week 👍🏻
