### ISSUE TITLE
Scheduling for publishing feature on Deploy v13 regression

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco.Deploy.Issues#233]
The Set date button on v13 doesn't work as expected - it will show right until you transfer it to the next environment then nothing is saved and therefore there's no schedule.

I have tested this on v8, v10, and v12 and it all works as expected.

![image](https://github.com/user-attachments/assets/a75f92b9-6cca-4372-b6b8-9937acd2cc6f)

Reproduction
------------
1. Create a document type with some content on a development environment
2. Push the changes over to the next environment + the content
3. Make a content change in the development environment
4. Queue it for transfer to the next environment and make sure to set a publishing date by using the Set date button
5. Transfer the content over to the next environment
6. Check the Scheduled time and see nothing is saved

### Specifics

This works fine on earlier versions of Deploy

### Expected result

To work as it worked in earlier versions

### Actual result

It doesn't save the scheduled selected time and instead publishes the content item instantly

---
_This item has been added to our backlog AB#43343_

**Comment by ronaldbarendse** [comment]
I've just released patch version 13.2.1 (and 14.1.2) to NuGet that fixes this issue, so you can manually upgrade your [Cloud](https://www.nuget.org/packages/Umbraco.Deploy.Cloud/13.2.1) or [OnPrem](https://www.nuget.org/packages/Umbraco.Deploy.OnPrem/13.2.1) project.
