### ISSUE TITLE
Umbraco Heartcore - Transfer Now - Open Transfer Queue button doesn't work

### ISSUE THREAD

**Issue by skidmow** [umbraco/Umbraco.Deploy.Issues#244]
When you execute a transfer via the "transfer now" button, it opens a new sidebar to execute the transfer. At the end of the process, a button appears reading "open transfer queue". If you click this button, nothing happens.

Reproduction
------------

### Bug summary

Broken "open transfer queue" button after using the "transfer now" feature.

### Specifics

Product: Umbraco Heartcore
Browser: Google Chrome (Version 131.0.6778.86 (Official Build) (arm64)

### Steps to reproduce

- Open a content node.
- Click the down arrow next to "save and publish"
- Click "transfer now"
- Start the transfer
- The transfer will process, then a button will appear titled "open transfer queue".
- Click the "open transfer queue" button.

### Expected result

The button click should redirect to Workspace tab and show the transfer queue.

### Actual result

Nothing happens. The click is unresponsive.

---
_This item has been added to our backlog AB#46901_

**Comment by AndyButland** [comment]
Thanks for reporting - we've fixed this now and the resolution will be in the next release of Deploy.
