### ISSUE TITLE
Member types hasn't same sort order on remote environment

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#3]
Base on Umbraco v8.12.1 it seems that when creating member types, the nodes in members section, may get a different sorting than on local environment.

I am not sure if the member tree nodes have sort order like content and member although they can't be sorted in the UI.
It may also be an issue in the Umbraco core itself.

Custom member types "Brand" and "Staff" created on local environment and looks like this in members section:

![image](https://user-images.githubusercontent.com/2919859/111960886-9adeaa00-8af0-11eb-9342-9e73784fca51.png)

Deployed to "live" environment on Umbraco Cloud where it looks like this:

![image](https://user-images.githubusercontent.com/2919859/111960984-b944a580-8af0-11eb-999b-5c397c5b2704.png)

Alternatively the trees should just be sorted in alphabetical order, but with "All Members" first.

**Comment by AndyButland** [comment]
I've fixed this with a PR to core to order the member types alphabetically when viewed in the "Members" section.  Currently no order is specified, so it's likey via numerical Id, which isn't something that can be adjusted via Deploy.

**Comment by AndyButland** [comment]
Will close this one now as the related PR has been merged into CMS `v8/contrib`, so will be resolved in the next CMS release (I assume a patch, but maybe next minor depending on where it gets targetted).
