### ISSUE TITLE
Content transfer progress bar doesn't move if initiated via a custom dashboard

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Deploy.Issues#39]
### Describe the issue
The content transfer/restore happens just like it should, however, the progress UI is stuck at 0.

## Specifics

Started on Deploy 3.5.2 and is also on 3.5.3.

Happens only with custom dashboards and if the custom dashboard is selected when the transfer is initiated.

You can see the entire transfer process in the log viewer in settings and confirm that it completes.

A simple workaround is to always select the Workspaces dashboard(SQUIGGLY SQUARE) before the transfer or to swap it out the custom one with it so that the original one is always first.

If you swap the dashboards in the UI, so you always have the Workspaces one first then it'll also work.

## Is it possible to Reproduce? 
Yes.

1. Have a custom dashboard(SQUIGGLY CIRCLE) like the one below
![image](https://user-images.githubusercontent.com/56826332/102091796-959dff00-3e1f-11eb-95b7-35ed2d4da17a.png)
2. Be on that custom dashboard
3. Initiate a content transfer/restore or transfer now via the Save & Publish dropdown
4. See the transfer progress bar not moving at all.

## Expected behavior
The UI actually shows the progress of the trasnfer.

## Screenshots
https://www.dropbox.com/s/oejh36pggh5ymco/J3mOlICsco.mp4?dl=0

## Additional context

_From SWAT #134_

**Comment by warrenbuckley** [comment]
Fixed in this PR https://github.com/umbraco/Umbraco-Deploy/pull/487
Due for release in 4.1.1
