### ISSUE TITLE
Get deployment errors into the detailed view in the error logs.

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco.Deploy.Issues#40]
### Describe the issue
While deploying some content, I see this error:

![image](https://user-images.githubusercontent.com/32164310/92110751-7852a100-edeb-11ea-91d6-97e905153a1f.png)

Which includes a lot of useful information!

BUT - I'd better copy it somewhere, since after I click the green "Okay" button, I won't be able to see it again.

If I look in the Log, this is all the info I get:

![image](https://user-images.githubusercontent.com/32164310/92110772-82749f80-edeb-11ea-9eb8-d9b171016bef.png)

image
![image](https://user-images.githubusercontent.com/32164310/92110836-a0da9b00-edeb-11ea-9ca5-99009f5a5947.png)

It would be great if all the error info were included in the log for later reference.

## Specifics

https://www.s1.umbraco.io/project/deploy-workshop

Umbraco 8.6.4
Forms 8.4.1
Deploy 3.4.5

Any environment that has had a deployment error failed.

## Is it possible to Reproduce? 
Then describe the steps below

Get a deployment error. Look at #99 for how to get one.
Navigate to log viewer.
Click on the error box:
![image](https://user-images.githubusercontent.com/32164310/92111715-ff544900-edec-11ea-9848-be626b47a9f4.png)

Find one with Deployment Failed, like this:
![image](https://user-images.githubusercontent.com/32164310/92111762-0f6c2880-eded-11ea-9e88-ab879bd99543.png)

## Expected behavior
I would expect the @MessageTemplate would contain the same information information that I am getting when I try and transfer content nodes with broken dependencies. Instead I get this:

![image](https://user-images.githubusercontent.com/32164310/92111893-45a9a800-eded-11ea-9e1c-6d4bc8c6191c.png)

## Additional context
**Proposed Error message:**
Having the same message from the portal page in the log viewer will help customers get to the same message which they then can show to support to help with the debugging if needed.

_From SWAT #100_

**Comment by nikolajlauridsen** [comment]
This has been fixed and will be in the next release 😄
