### ISSUE TITLE
Setting a different language as default breaks deploy

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Deploy.Issues#44]
Reproduction scenario:

- Create new cloud site
- Add a language on live (for instance dutch)
- Set the new language as default
- Add a dev environment

The dev environment now has a deploy error.
The way to solve it is go into the dev environment, manually add the language, set as default and echo > deploy

After that everything is fine. This should be automated in my opinion.

**Comment by nul800sebastiaan** [comment]
Thanks @FransdeJong - this should be fixed in 4.1.1 - https://github.com/umbraco/Umbraco.Deploy.Issues/issues/32
Not sure when it will be out but I imagine it won't be long :-)

_Ps. FYI: I've moved this issue to the new Deploy issue tracker_
