### ISSUE TITLE
Umbraco.CheckBoxList data type not syncing

### ISSUE THREAD

**Issue by saadan** [umbraco/Umbraco.Deploy.Issues#45]
When Im trying to add new prevalues to a checkBoxList property an sync with live the selected values on live get deselected.

Reproduction
------------

- Add a Umbraco.CheckBoxList property to a document type and add some pre-values
- Sync the new pre-values to cloud (e.g. Local to Live) 
- Create a node on live with the property and select a value from the checkBoxList
- Go back to the local environment and add a new pre-value to the Umbraco.CheckBoxList property
- Sync the new pre-values to cloud again
- Now if you look at the live environment and find the node where the checkBoxList property should have a selected value it has been deselect visually.

### Expected result

The property on the destination environment should have the same selected value as before the second sync.

### Actual result

The property on the destination environment doesn't have a selected value after second sync.

the issue looks alot like this https://github.com/umbraco/Umbraco.Cloud.Issues/issues/20

**Comment by nul800sebastiaan** [comment]
Thanks for the bug report with exact steps! And apologies for taking so long to have a look at this one 😬 

I have been able to reproduce this now, even in the latest version. Here's what I can see happening:

My checkbox list, before deploy from local to live looks like this (when loading the content page in the backoffice, so this data is coming back from `/umbraco/backoffice/UmbracoApi/Content/GetById?id=1053`): 

```javascript
		"label": "Check list",
		"description": null,
		"view": "checkboxlist",
		"config": {
			"items": {
				"22": {
					"value": "test1",
					"sortOrder": 1
				},
				"23": {
					"value": "test4",
					"sortOrder": 2
				},
				"24": {
					"value": "test2",
					"sortOrder": 3
				},
				"25": {
					"value": "test6",
					"sortOrder": 4
				},
				"26": {
					"value": "test3",
					"sortOrder": 5
				},
				"27": {
					"value": "test5",
					"sortOrder": 6
				},
				"28": {
					"value": "test7",
					"sortOrder": 7
				}
			}
		},
		"hideLabel": false,
		"validation": {
			"mandatory": false,
			"pattern": null
		},
		"readonly": false,
		"id": 7,
		"dataTypeId": "fbaf13a8-4036-41f2-93a3-974f678c312a",
		"value": ["22", "23", "24", "25"],
		"alias": "checkList",
		"editor": "Umbraco.CheckBoxList",
		"isSensitive": false
	}],
```

After adding another prevalue (`test8`) and deploying that to Live, surprisingly, I see the exact same coming back from `/umbraco/backoffice/UmbracoApi/Content/GetById?id=1053`. However, none of the checkboxes are checked, as reported.. 😞 

But I also don't see `test8`, so something else is wrong. I figure it's some kind of caching issue, so after restarting the site I checked again: `test8` has appeared, but nothing is checked.

So then having another look at the response from `/umbraco/backoffice/UmbracoApi/Content/GetById?id=1053` I now see the following: 

```javascript
		"label": "Check list",
		"description": null,
		"view": "checkboxlist",
		"config": {
			"items": {
				"29": {
					"value": "test1",
					"sortOrder": 1
				},
				"30": {
					"value": "test4",
					"sortOrder": 2
				},
				"31": {
					"value": "test2",
					"sortOrder": 3
				},
				"32": {
					"value": "test6",
					"sortOrder": 4
				},
				"33": {
					"value": "test3",
					"sortOrder": 5
				},
				"34": {
					"value": "test5",
					"sortOrder": 6
				},
				"35": {
					"value": "test7",
					"sortOrder": 7
				},
				"36": {
					"value": "test8",
					"sortOrder": 8
				}
			}
		},
		"hideLabel": false,
		"validation": {
			"mandatory": false,
			"pattern": null
		},
		"readonly": false,
		"id": 7,
		"dataTypeId": "fbaf13a8-4036-41f2-93a3-974f678c312a",
		"value": ["22", "23", "24", "25"],
		"alias": "checkList",
		"editor": "Umbraco.CheckBoxList",
		"isSensitive": false
	}],
```

The problem, as we can see now, is that the identifier for each prevalue item has change, `test1` changed from `22` to `29`, `test2` from `23` to `30`. This doesn't match up with the array of selected values any more `["22", "23", "24", "25"]`. 

Not sure why the identifiers have been updated but that's probably a mistake, no need to change them.
