### ISSUE TITLE
Content Restore Progress

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Deploy.Issues#47]
Recently spun up an 8.12.2 site and cloned locally.

After a bit of to-and-fro I needed to to a full restore to local from live.

The progress panel just sat there saying it was collecting items from Live, but never updates from there.

![image](https://user-images.githubusercontent.com/42397042/115320320-00dc5100-a1c5-11eb-89f8-34a58a5faee9.png)

After an interminable wait, I needed to check the logs on the Cloud site to verify that the deploy had actually succeeded, and it was ok to refresh the page on the local site and reload the content panel. The deploy was apparently complete, but no indication of the progress or status was given.

I've tried this a number of times now, and always with the same result.

**Comment by AndyButland** [comment]
Resolved via [this commit](https://github.com/umbraco/Umbraco-Deploy/commit/ad1d87d0cf3ec3d6fcaf8e30de162b93eb71acbb).

**Comment by c9mbundy** [comment]
@AndyButland - Yes - I was trialing a copy of the latest starterkit from uSkinned, which definitely installs a custom dashboard ahead of the deploy - but then again that's a pretty common place thing to do.

**Comment by AndyButland** [comment]
Agreed, it's a common problem (we see it with Uno for example).  But good to know it sounds ike the same issue - thanks for confirming.
