### ISSUE TITLE
List multiple dependency errors when deploying or restoring

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco.Deploy.Issues#5]
Currently, if you try to restore or deploy a section in which there are multiple dependency errors, Umbraco will only tell you about the first one it encounters. This means that the user must fix an error, try again, and repeat to fix all errors, which can be very time consuming.

It would be much better if Umbraco kept searching for dependency errors after the first one is encountered, and told the user about all of them at once.

**Comment by FransdeJong** [comment]
Is there any update on this issue?
This is by far the most time consuming issue with deploy at the moment.
Especially for larger sites.

**Comment by AndyButland** [comment]
Thanks for pinging this issue and bringing it to my attention.  I've had a look today at what we could do here.

Firstly, the undocumented settings should shortly be documented from the PR I've raised and linked above.

Then for the feature itself, seemed that we could fairly easily:

- Not throw on the first exception, but to check for all dependency issues and throw an aggregate exception containing details of all of them.
- Expose this better in the user interface, so it's not so buried in the "technical information".

What I've been working on looks like this:

![image](https://user-images.githubusercontent.com/1993459/125792702-f0f49618-cb0e-4ab5-9bd1-51b5bb83c4a6.png)

It's still a tricky one to make completely "editor friendly", as sometimes there's not much information to display - e.g. for a deleted media item, we only really have the UDI, but this should still be an improvement in making it a bit more accessible and readable.

**Comment by warrenbuckley** [comment]
Fixed in this PR by Andy - https://github.com/umbraco/Umbraco-Deploy/pull/570
Due for release 4.2.0
