### ISSUE TITLE
Install-Package : Unable to resolve dependency 'UmbracoDeploy'.

### ISSUE THREAD

**Issue by prosperva** [umbraco/Umbraco.Deploy.Issues#55]
### Which Umbraco version are you using?

8.6.3

### Bug summary

Tried installing mbracoDeploy.Contrib Version 3.0.3 but when I ran: Install-Package UmbracoDeploy.Contrib -Version 3.0.3, I got Install-Package : Unable to resolve dependency 'UmbracoDeploy'. error.

I have already installed Umbraco Deploy

### Steps to reproduce

1. Install-Package UmbracoDeploy.OnPrem
2. Install-Package UmbracoDeploy.Contrib -Version 3.0.3

**Comment by AndyButland** [comment]
Hi @prosperva - apologies for the mix-up there.  I've resolved the dependency issue now and released an update (version 4.0.0) to NuGet that you should be able to install from here: https://www.nuget.org/packages/UmbracoDeploy.Contrib

The contrib project is compatible with Deploy On-Premises, so you are welcome to use it in your setup if you need it for one of the data types it provides connectors for.
