### ISSUE TITLE
Add support for dictionary item deployment "as content", in the same way that form data can be configured

### ISSUE THREAD

**Issue by lucasmichaelsengorm** [umbraco/Umbraco.Deploy.Issues#56]
Hello,

We are facing an issue with Umbraco Deploy On Prem.
In general it works as expected, but when a Content Editors making UDA changes, we are facing a challenges, wicth after a talk with Denial from support there is no solution for.

Our setup. We have our local UDV machine, where we do our code, and push it up to a git reposority.
When we have made any changes along with UDA changes, we trigger a deploy, wicht deploy the code from GIT hub to the servers.
! [image] (https://user-images.githubusercontent.com/69140700/121179391-fe5eb500-c85f-11eb-9068-dbf9da7d393f.png)

All the servers are standing in a DM-Zone and do not know anything about each other.

Let us say, I on my local machine, makes a new nested content, along with a dictionary, and the Translation have I spell a word "Gomorning", and commit all my changes to the GIT Repo, and deploy it to staging for the customer can test it before production.

The customer sees my spelling mistake and making a change on the dictionary item, from "Gomorning" to "Godmorning", on the staging server. The UDA-file while now be changes, but now there is a problem, how do we get the changes UDA file from Staging server to Production, or keep the change?

When talking to the Umbraco Support I only got that, the solutions is to go to the server, and ZIP the Data folder, and add it to my local machine and the make new deploy. But here there is coming some inconvenience for the customer.

They either need to contact there IT-department to take a copy of the Data folder, and add to the git repo, and trigger a deploy,
Or they still need to contact the IT department to take a copy of the Data folder, and send it to the developer company, and they a being charged for we add it to the git repo, and trigger a deploy.
Either solution is time consuming, and or expensive, and the IT department getting it and other task, in the already busy schedule of "why do my computer not working", or "I can not print" helpdesk cases.

As a Feature Request, is that the deploy, is not making any UDA-files, but all translations, data-types, doctype and more, is handles as content like Umbraco Forms, and UDA files is not exiting anymore, on the way, the Content editors can just edit the translation, and transfers it as they are used to with the content.

**Comment by nul800sebastiaan** [comment]
Thanks @lucasmichaelsengorm, we'll need to discuss this at HQ and will get back to you. To set some expectations, I hope you understand we're quite busy with CodeGarden coming up in a few days, so I don't expect more feedback for you to come in this week.

**Comment by AndyButland** [comment]
Hi @lucasmichaelsengorm - just to firstly expand on what you've noted above, here's the full details of what I shared with the support team when they escalated your query earlier.

With Deploy On-Premises, anything deployed as "schema", which includes dictionary items by default, need to be committed into source control.  So in this scenario, yes, you would need to obtain the updated `.uda` files from the development server where they have been updated by editor action, copy them down locally and check them into source control.

By doing that, it would prevent them getting overridden with the previous values on the next deployment.

As an alternative, you could also exclude dictionary items from deployments, with a settings update like this:

```
	<excludedEntityTypes>
		<add type="dictionary-item" />
	</excludedEntityTypes>
```

This would mean editors could make updates in any environments without them getting overridden.  But of course you then need to make the updates in each environment without the help of Deploy.

There's a third option, which is to have dictionary items deployed as content - like you have the option to do with Forms.  With this setup, dictionary items could be deployed via the back-office - so not via `.uda` files and source control, but via back-office transfers and restores in the same way that content is.  That needs careful control over which way transfers are done to make sure not to overwrite changes, but would support developers creating new values and deploying them, and editors updating them in higher environments.

Unfortunately this option can't be configured currently (there's a `transferFormsAsContent` setting but not an equivalent for dictionary items).  So we'd need to do a bit of work and release to support this, but it should be fairly straightforward as it would follow what's available for Forms.

So in short it doesn't seem there's currently an ideal solution here.  Rather you would need to decide if dictionary items are deploy managed and developer controlled, with a manual step to get the updates from editors if they know they have made them.  Or turn off deploy of dictionary items and leave them in manual, editor control in each environment.

I hope we can fairly soon support this middle option of back-office transfers though - at least for dictionary items.  Although also feasible, I'm not convinced that promoting back-office deployments of document types for example is a good idea, in that they should be aligned with and deployed with code.  But dictionary items do have a clearer reason for deployment in this way - as you note they being often created by developers but updated by editors.

With your permission I'll re-title this issue to describe that amend and we can track it here.

**Comment by lucasmichaelsengorm** [comment]
Hi @AndyButland,

Thank for your comment, but I not looking for a quick or dirty fix, but something strong and feature proff.

Unfunturrenly dictionary items is not the only thing, witchs is the problem, the customer who have the Deploy on Prem, do have a DataType "Multiple Dropdown", witch containing tags, they want control instead of the datatype "Tag" where endless coas can occere, so whenever the want to add a new Year, in the tag dropdown, the Administrator goes to the staging server adds the tag and need to push it to production, here again they are stuck.

An access to there servers is prohibit, only to the selected few from the IT-department, and only the whiteliste programs are allowed on it. It is DMZ server, witch is strict hard, so GIT from the server is not an option. 
So when the marketing deparment makes a changes to etiher dictionary or data type, the need to add a helpdesk cases, and wait to the IT-department have time, to resolve this. 

If we developers takes control over the data types or dictionary the Customer always need to write to a delevoper, wait for an awsner and solution and deploy, but that will end up in 2 hours bills each time, to the customers, with the woundring queistion why should we pay 2 hours each time, and wait 24hour for a solution, when Content freely can be tranfers between server withour a problem? (We already got this question) Along the IT-deparment (Why do we need this task on our desk?)

**Comment by warrenbuckley** [comment]
Merged in this PR
