### ISSUE TITLE
Refresh button on queue

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Deploy.Issues#61]
Can we have a refresh button here?

![image](https://user-images.githubusercontent.com/3726467/124266064-c54ff280-db36-11eb-86be-a99e0b1e50be.png)

Right now, I click away from the dashboard, and then click to the dashboard again to refresh.

Especially useful, if you have one browsertab for adding stuff to the queue, and another one for deploying.

**Comment by AndyButland** [comment]
Yes, good point.  We have a refresh button I see, but it's only visible when there are no items in the queue - and, as you say, it's useful even when there are already items for transfer.

A quick fix so we'll get that in the next release.
