### ISSUE TITLE
Feature Request: Tools to compare Content/Media/etc. between environments to facilitate transferring

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#65]
I'm a big fan of Umbraco Deploy. There are a couple of pain points I have come across however, working on multiple different clients and Umbraco versions. Some of these are especially painful when doing large developments such as migrations of old sites to Umbraco Cloud, v7 to v8 migrations, etc.

## Challenges ##
1. Doing a lot of small content updates across many nodes... then needing to remember which nodes were changed and transfer them.
2. As a developer, not being aware when you should be pulling updated content from Dev to Local, since Dev changes are happening without your awareness.
3. Working with multiple developers/content editors and accidentally overwriting Content node changes on Destination environments via Deploying. (related to previous item)

## Suggested Solutions ##

I think there could be some great tooling to assist with these (and other) issues. A few specific things I've thought about...

**In the transfer queue:** An option to compare source and destination nodes before finalizing the transfer - The things I would love to see would be "last edited date" on each and "last edited by user" on each. If something was updated on Dev just a day or so ago, I might think twice about overwriting that with something from my local environment. Also, if I see that a Content Editor worked on a node, that would be something I'd want to be careful about not overwriting as well. Whereas, if I was the last one to edit the destination node (perhaps via a prior deployment?) then I'd feel confident overwriting the destination node. It would be good to be able to remove an item from the transfer after this comparison, but before the transfer occurs. This sort of UI would likely mean a deployment would take longer, so perhaps it is an option that can be used or not on each deployment transfer.

**Dashboard Tool:** It would be nice to be able to do a similar sort of comparison across all the content in the site in a single interface, with a button next to each node to "Add to Transfer Queue" This would make it easier to get a large quantity of small changes gathered up at one time for transfer. Additionally, if it could show nodes which exist on the destination environment, but not on the current one, those could be "restored".

**Info Tab or Content App:** Information about when a node was last deployed, or updated via a deployment as part of the information available about the node, on the node. Could be part of the Audit log (see: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/22)

**Deploy API/Event Access:** If some aspects of Deploy were opened up via an API and Events, many of these things could be built by us devs ourselves 😁 If there was a Service which I could use to "Read From Environment",  "Add to Transfer Queue" or "Deploy Now", I could create some of these tools today. (see also: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/36)

**Comment by AndyButland** [comment]
A part of this at least will be made available by a "content compare" feature due in the next release.  I'll close based on that, and then perhaps we can look at spinning off further issues if there are extensions to it that seem useful and feasible to implement.

**Comment by hfloyd** [comment]
Thanks, @AndyButland I look forward to seeing what you've got :-)

**Comment by hfloyd** [comment]
@AndyButland Do you have an ETA on a first release of your new "content compare" feature?

**Comment by AndyButland** [comment]
[There's an RC available](https://umbraco.com/blog/release-candidates-umbraco-forms-81193-and-deploy-4593/) that was out a week or so ago, with the final release expected on 8th March,

**Comment by hfloyd** [comment]
Thanks, @AndyButland , what a nice birthday gift you have planned for me 😍
I missed the RC post, and I see it says:

> If you are using Umbraco Cloud and are happy to run some tests there, please reach out to Umbraco support and we can make available the files to run the RC on your project.

So I will do that today.

**Comment by hfloyd** [comment]
Hi again, @AndyButland So, I got the RC installed on a 9.3 Cloud site. It works as designed, and I have added a few thoughts here: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/101 

This is a good start. but it really doesn't solve my main challenges (outlined, above). As per your suggestion, above, I will create separate specific feature requests for additional tools which would be helpful to me, personally, and if others like the ideas, they can add comments as well.

**Comment by AndyButland** [comment]
Thanks @hfloyd - that sounds ideal.

**Comment by hfloyd** [comment]
So, @AndyButland I realized I could make a start on :

> **Dashboard Tool:** It would be nice to be able to do a similar sort of comparison across all the content in the site in a single interface, with a button next to each node to "Add to Transfer Queue" This would make it easier to get a large quantity of small changes gathered up at one time for transfer. Additionally, if it could show nodes which exist on the destination environment, but not on the current one, those could be "restored".

but it's still somewhat inefficient to actually use without any way to interact with the Deploy queuing. So, here is my new request: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/105 😁
