### ISSUE TITLE
Creating a new page result in 404 error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#68]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

On a clean Umbraco Cloud project based on v8.15.1 I am getting an 404 error when using the "create" action to create a content node.

### Steps to reproduce

Create a new page at root level, e.g. a Home Page.
An error notification is shown.

![image](https://user-images.githubusercontent.com/2919859/130574639-605dab4e-ee5f-4bfa-b4f7-d6eedd017369.png)

**Comment by nul800sebastiaan** [comment]
Transferred! Weird, so it's a local clone of the cloud project that is problematic, on Cloud itself it works?

**Comment by bjarnef** [comment]
@nul800sebastiaan yes, on local environment, but probably also on development or staging environment, which has the option to deploy/transfer content/media.

**Comment by AndyButland** [comment]
Thanks for the sleuthing @bjarnef, I can replicate.  I think the issue here is that this code shouldn't be running on the "create" of a content item.  It's adding the "Transfer Now" sub-button to the "Save and Publish" button, but that won't work anyway until the content is saved.  So I've added it now only for editing existing nodes.

**Comment by bjarnef** [comment]
@AndyButland it probably doesn't need to look up content either if `$routeParams.id` is lower than zero.

**Comment by AndyButland** [comment]
No, but it won't if you are editing content.  When creating the value in `$routeParams.id` is the parent of the content, so that's why you get this issue when creating content at the root.  When editing, it's the actual content, which will have a valid id.

So I think we just need this:

```
if ($routeParams.section === "content" && $routeParams.create !== "true") {
```

**Comment by bjarnef** [comment]
Yeah, that would work.

`/umbraco/#/content/content/edit/-1?doctype=homePage&create=true`

However wrapping with an additional check wouldn't harm - just in case.

```
if ($routeParams.id > -1) {
  // Only add the "transfer now" button if the user has permissions to "queue for transfer".
  contentResource.getById($routeParams.id).then(function (content) {

 });
}
```

Actually I noticed this throws as exception if changing id in route to e.g. zero, but probably more a core issue:
/umbraco/#/content/content/edit/0?doctype=homePage&create=true

![image](https://user-images.githubusercontent.com/2919859/130604707-208be274-2353-4753-92e0-bdc768724bb1.png)

without the querystring:

![image](https://user-images.githubusercontent.com/2919859/130604768-c4fd46dd-9d38-49c7-846a-85c316888260.png)
