### ISSUE TITLE
Nodes with ListViews should be able to queue child nodes for transfer

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Deploy.Issues#9]
_From @jizepi on October 3, 2018 8:18_

See original bug on previous tracker at https://issues.umbraco.org/issue/U4-11063

Nodes with ListViews should also offer the option to queue child nodes for transfer. No reason not to be able to send the children of a node with list view.

Currently having to open many nodes individually to queue them all for transfer, which is something of a pain point.

_Copied from original issue: umbraco/Umbraco-CMS#3131_

**Comment by AndyButland** [comment]
Checking the latest version (4.1) I can see this does looks have been resolved:

![image](https://user-images.githubusercontent.com/1993459/113701587-a2997380-96d8-11eb-9ec7-8a9290170636.png)

So will close this issue now.
