### ISSUE TITLE
Link to open project on Umbraco.io doesn't work

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Deploy.Issues#94]
On the Workspaces tab, when you click the **Live workspace** there is a "Manage Workspace" section with a link to *Open {project_alias} on Umbraco.io* - this links to a non-existent URL, thus you end up on the `/projects` screen instead.

This is in **Umbraco 9.1.2 with Deploy 9.2.0**

The URL on the link is constructed like this: `https://www.umbraco.io/project/{project_alias}`

This link works correctly in **Umbraco 8.13.1 with Deploy 4.1.4)** where it is constructed like this: `https://www.s1.umbraco.io/project/{project_alias}`

So seems to be missing the `s1` subdomain in the hostname.

**Comment by AndyButland** [comment]
Thanks for reporting - and yes, you're exactly right, the domain name being used isn't correct.  I've updated it so it'll be fixed for the next release.  I'll mark for 9.2.1 though it'll maybe be in 9.3 if that's ready before we do a patch.
